version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 301190
      POSTGRES_DB: anoneanone
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=anone.settings.devw
    volumes:
      - .:/backend/
    ports:
      - "8000:8000"
    depends_on:
      - db