# Generated by Django 3.0.3 on 2020-04-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0002_auto_20200311_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranobe',
            options={'ordering': ['id']},
        ),
    ]
