# Generated by Django 3.0.3 on 2020-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0002_auto_20200311_1631'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='planned_books',
            field=models.ManyToManyField(related_name='planned', to='ranobe.Ranobe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='read_books',
            field=models.ManyToManyField(related_name='read', to='ranobe.Ranobe'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reading_books',
            field=models.ManyToManyField(related_name='reading', to='ranobe.Chapters'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='media/profile'),
        ),
    ]
