# Generated by Django 3.0.3 on 2020-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0002_auto_20200311_1631'),
        ('users', '0002_auto_20200312_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarked',
            field=models.ManyToManyField(related_name='bookmarked', to='ranobe.Ranobe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/profile/default.png', null=True, upload_to='media/profile'),
        ),
    ]
