# Generated by Django 3.0.3 on 2020-04-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0003_auto_20200401_1109'),
        ('users', '0003_auto_20200320_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHOICES', models.CharField(choices=[('RDG', 'Читаю'), ('RD', 'Прочитано'), ('PD', 'Запланировано')], max_length=3)),
                ('ranobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.Ranobe')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='read_status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='users.ReadStatus'),
        ),
    ]
