# Generated by Django 3.0.3 on 2020-04-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200401_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='read_status',
        ),
        migrations.AddField(
            model_name='readstatus',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
            preserve_default=False,
        ),
    ]
