# Generated by Django 3.0.3 on 2020-04-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200401_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='read_status',
        ),
        migrations.DeleteModel(
            name='ReadStatus',
        ),
    ]
