# Generated by Django 3.0.3 on 2020-04-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0003_auto_20200401_1109'),
        ('users', '0009_auto_20200401_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReadingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('ranobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.Ranobe')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='read_status',
            field=models.ManyToManyField(related_name='book_status', through='users.BookReadingStatus', to='ranobe.Ranobe'),
        ),
    ]
