# Generated by Django 3.0.3 on 2020-04-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200401_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreadingstatus',
            name='choices',
            field=models.CharField(choices=[('NO', 'Не выбрано'), ('RDG', 'Читаю'), ('RD', 'Прочитано'), ('PL', 'Запланировано')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
