# Generated by Django 3.0.5 on 2020-04-16 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0003_auto_20200401_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_bookreadingstatus_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/profile/default.jpg', null=True, upload_to='media/profile'),
        ),
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.Ranobe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
