# Generated by Django 3.0.5 on 2020-04-16 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranobe', '0003_auto_20200401_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20200416_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readhistory',
            name='ranobe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.Chapters'),
        ),
        migrations.AlterField(
            model_name='readhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
