# Generated by Django 3.0.5 on 2020-04-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200416_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readhistory',
            old_name='ranobe',
            new_name='ranobe_chapter',
        ),
    ]
