# Generated by Django 3.0.5 on 2020-04-18 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranobe', '0003_auto_20200401_1109'),
        ('users', '0014_auto_20200416_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='planned_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='read_books',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reading_books',
        ),
        migrations.CreateModel(
            name='RanobeLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.SmallIntegerField(choices=[(-1, 'Like'), (1, 'Dislike')])),
                ('ranobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranobe.Ranobe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
